### ISSUE TITLE
Ale46 can i use to SITube-Downloader project to make a full fledge java downloader

### ISSUE THREAD

**Issue by siddht4** [Ale46/SITube-Downloader#3]
Ale46 ,

i need your permission to able to use your SITube-Downloader project into a full fledge java downloader ,  currently what i have in mind is to mimic functionality as rg3  https://github.com/rg3/youtube-dl project as its in python and i can possibly re code it in java . 

i have done some work to call the python project in java  https://github.com/siddht1/youtube_dl_java_old  and now planning to make a full fledge independent java project  https://github.com/siddht1/youtube_dl_java .

**Comment by Ale46** [comment]
All the code is released under the [GNU Public License v2.0](http://www.gnu.org/licenses/old-licenses/gpl-2.0.html), so if you respect the [license rules](https://tldrlegal.com/license/gnu-general-public-license-v2) you can do whatever you want. Anyway remember that this code is about five years old and was developed in my 20s, expect a lot of spaghetti code and "strange" things. 
Apart from that happy coding & good luck with your project!

**Comment by siddht4** [comment]
@Ale46  thank you for the approval . I asked you as there was no license metioned on your repo. I  have started work to migrate your project from gui to a text one as first I will build it in simple io then will add the gui , so two branches will be made . 

As i have your code as a base and I already understand your code , that is why i was able to fix the java error https://github.com/Ale46/SITube-Downloader/pull/2. I respect the https://tldrlegal.com/license/gnu-general-public-license-v2  so it was my way for acknowledging  your approval and let you know what are my plans , changes , So you have an idea beforehand.

`Anyway remember that this code is about five years old and was developed in my 20s, expect a lot of spaghetti code and "strange" things.`
 If there is some exception or error I may need your help.

`Apart from that happy coding & good luck with your project!`

Thank you , now i can technically upgrade your code
